name: 'Copilot Potential User Report Action'
description: 'Uncover the untapped potential within your team by identifying members who could benefit from using GitHub Copilot!'
branding:
  icon: trending-up
  color: blue
inputs:
  pat: 
    description: 'Personal Access Token'
    required: true 
  slug_type: 
    description: 'Slug Type (enterprise or organization)'
    required: true 
    default: 'organization'
  slug_name:
    description: 'Enterprises or Organizations Name'
    required: true 
    default: 'avocado-corp'
  audit_log_included:
    description: 'Include audit log (true or false) - optional, default is true'
    required: false
    default: 'true'
outputs:
  summary:
    description: 'Brief summary of the Copilot opportunities'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PAT: ${{ inputs.pat }}
    SLUGTYPE: ${{ inputs.slug_type }}
    SLUGNAME: ${{ inputs.slug_name }}
    AUDIT_LOG_INCLUDED: ${{ inputs.audit_log_included }}